name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey there! Thanks for submitting your first issue with LOD. Someone will triage this shortly.'
        pr-message: 'Hey there! Thanks for opening your first PR for LOD. Someone will review it shortly.'
